FROM golang:alpine

RUN apk update && apk upgrade && apk add --no-cache bash git openssh gcc

COPY /ImageCutter /go/src/ImageCutter
WORKDIR /go/src/ImageCutter/pkg/integration_tests

ENV CGO_ENABLED=0
ENV GO111MODULE=on
RUN go mod download

CMD ["go", "test", "-v"]