# Pull nginx base image
FROM nginx:latest

# Expost port 80
EXPOSE 80

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static
COPY ./nginx_images /static

# Start up nginx server
CMD ["nginx"]

# docker build -f Dockerfile_nginx -t cutter_nginx .
# docker run -p 80:80 --rm --name CN cutter_nginx